### ISSUE TITLE
Get Colors working

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Semagrams.jl#23]
Self-explanatory

**Comment by jpfairbanks** [comment]
There should be other style options patterned on GraphViz. For example this figure that AlgebraicPetri can make for showing subobjects (monomorphisms) via changing the stroke width is really useful. 

<img width="503" alt="Screen Shot 2021-08-05 at 1 00 36 PM" src="https://user-images.githubusercontent.com/2753998/128391023-6c395aae-60a1-44aa-8b72-635ffe5103d5.png">
