### ISSUE TITLE
KaTeX support

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Semagrams.jl#29]
Schemas should have something which calls out an attribute as a "labelling attribute", and then the value of this is used to make a KaTeX label

**Comment by epatters** [comment]
I assume this special attribute, or rather its KaTeX label, would appear inside the box?

**Comment by olynch** [comment]
Closed by 0055bf3ae2eaac0bb0e7c1f09464d3a0ad64b7f0
