### ISSUE TITLE
Layout Grid Controlled by Single Instance

### ISSUE THREAD

**Issue by bosonbaas** [AlgebraicJulia/Semagrams.jl#38]
I've noticed that when there are multiple semagram instances open on the same jupyter-lab instance (regardless of whether they're in different notebooks), the background grid is only controlled by one of them. The grid on all other instances will be unmoved by dragging (though the objects themselves are), and the background grid on all of them will shift and scale as it's changed on the first instance.

**Comment by olynch** [comment]
Not relevant for Semagrams next.
