### ISSUE TITLE
Support for data attributes

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Semagrams.jl#4]
In practice, acsets almost always have data attributes, e.g., Petri nets might have labels for the states and/or transitions and rate constants for the transitions.

Editing attributes with Semagrams could become arbitrarily sophisticated, but I figure that to get started it would be enough to have editing support for text attributes (`String` and `Symbol`) and numeric attributes (`Int` and `Float*`).

**Comment by olynch** [comment]
I'm not going to close this until I get attributes for wires working, #12 did not get this.

**Comment by olynch** [comment]
Also, the numerical input needs to be more user-friendly; it should show the current number, and also allow setting of max/min for the slider.
