### ISSUE TITLE
[BUG] Step 1 of Extended Introduction Failing

### ISSUE THREAD

**Issue by TheCedarPrince** [AlgebraicJulia/Semagrams.jl#45]
Hi all,

Thanks for the extended tutorial! I am probably missing something but am running into the following error on [step 1](https://github.com/AlgebraicJulia/Semagrams.jl/blob/main/docs/src/index.md):

When writing the following Julia snippet:

```julia
using Catlab
using Semagrams

@present TheoryReactionNet(FreeSchema) begin
  (T,S,I,O)::Ob
  it::Hom(I,T)
  is::Hom(I,S)
  ot::Hom(O,T)
  os::Hom(O,S)
  N::Data
  rate::Attr(T,N)
  concentration::Attr(S,N)
end
```

I get this error traceback:

```julia
ERROR: UndefVarError: FreeSchema not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/Catlab/5eZgn/src/core/Present.jl:213
```

Was something needed to be defined somewhere? What am I missing? Thanks!

~ tcp

**Comment by sjbreiner** [comment]
You'll need to include the following imports:
```
using Catlab.Present				# defines @present macro
using Catlab.CSetDataStructures		# defines FreeSchema
```

**Comment by sjbreiner** [comment]
Added imports for @present and FreeSchema before the first usage in the docs.

**Comment by TheCedarPrince** [comment]
That worked here - thanks @sjbreiner
