### ISSUE TITLE
Error Handling for Graph Types

### ISSUE THREAD

**Issue by TheCedarPrince** [AlgebraicJulia/Semagrams.jl#47]
Based on issue #46 i t seems like the error traceback could be better improved by changing from what was said in the traceback for using the incorrect graph types here:

```julia
ERROR:   error: all type parameters to the acset type must be fully instantiated.

  Right: Semagram{WeightedGraph{Int}}(WeightedGraphSema)
  Wrong: Semagram{WeightedGraph}(WeightedGraphSema)
```

To something like this:

```julia
ERROR:   all type parameters to the acset type must be fully instantiated. 

Ensure that you are `using Catlab.Graphs`.
```

As in the traceback, this gets around the specifics of the graph type and makes it much more broader. In theory, I could imagine it linking back to documentation in some way. I really like the idea of this error handling and I think you should keep going with it! Great work!

**Comment by jpfairbanks** [comment]
Is this error message just saying that you need to do `using Catlab.Graphs`? I guess this is another pain point related to #44.

**Comment by sjbreiner** [comment]
Hi James,

That's not in the error message now. That was my suggestion for fixing the error "WeightedGraph not found"

**Comment by jpfairbanks** [comment]
Yeah, I think we should fix the fact that using Semagrams without also using Catlab and Catlab.CategoricalAlgebra and Catlab.Graphs causes a bunch of weird errors as the upstream problem to this inaccurate error message.

**Comment by olynch** [comment]
This is not relevant for next, closed.
